var Data = {
    URL: "",
    SMARTMYTHTVVERSION: "SmartMythTV 0.4.3",
    Titles: [],
    GroupsGroupTitles: [],
    GroupsMemberTitles: [],
    GroupsRecordings: [],
    UpcomingList: [],
    UpcomingDetail: [],
    Recordings: [],
    VideoTitles: [],
    Videos: [],
    loaded: 0,
    loadedGroups: 0,
    loadedUpcoming: 0,
    loadedRecordings: 0,
    loadedVideos: 0,
    max: 0,
    maxVideos: 0,
    currentStream: 0,
    startGroups: 0,
    mainScene: ""
};
