var Data = {
    URL: "",
    SMARTMYTHTVVERSION: "SmartMythTV 0.4.0",
    Titles: [],
    GroupsList: [],
    GroupsGroupTitles: [],
    GroupsGroupCount: [],
    GroupsRecordings: [],
    UpcomingList: [],
    UpcomingDetail: [],
    Recordings: [],
    VideoTitles: [],
    Videos: [],
    loaded: 0,
    loadedGroups: 0,
    loadedUpcoming: 0,
    loadedRecordings: 0,
    loadedVideos: 0,
    max: 0,
    maxVideos: 0,
    currentTitle: "",
    currentRecording: 0,
    currentVideo: 0,
    streamURL: "",
    startGroups: 0,
    mainScene: ""
};
