var Data = {
	URL : "",
	SMARTMYTHTVVERSION : "SmartMythTV 0.3.0",
	Titles : [],
	GroupsList : [],
	GroupsGroupTitles : [],
	GroupsGroupCount : [],
	GroupsRecordings : [],
	Recordings : [],
	VideoTitles : [],
	Videos : [],
	loaded : 0,
	loadedGroups : 0,
	max : 0,
	maxVideos : 0,
	currentTitle : "",
	currentRecording : 0,
	currentVideo : 0,
	streamURL : "",
	startGroups : 0,
	mainScene : ""
};